import { chromium } from 'playwright';
const base='http://localhost:8087';const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2});const p=await ctx.newPage();
const user={sub:'auth0|shots',name:'Mobile Shots',email:'s@e.com',picture:''};
const script=`(()=>{const u=${JSON.stringify(user)};const a={ready:Promise.resolve({isAuthenticated:true}),resolve:()=>Promise.resolve({authenticated:true,user:u}),requireAuth:()=>Promise.resolve({status:'authenticated',user:u}),guard:()=>Promise.resolve({status:'authenticated',user:u}),isAuthenticated:()=>Promise.resolve(true),getUser:()=>Promise.resolve(u),getAccessToken:()=>Promise.resolve('t'),signIn:()=>Promise.resolve(),signOut:()=>Promise.resolve()};window.DEX_AUTH=a;window.dexAuth=a;window.AUTH0_USER=u;window.auth0Sub=u.sub;window.auth0={getUser:()=>Promise.resolve(u)};try{window.dispatchEvent(new CustomEvent('dex-auth:ready',{detail:{isAuthenticated:true,user:u}}))}catch{}})();`;
await p.route('**/assets/dex-auth.js',r=>r.fulfill({status:200,contentType:'application/javascript',body:script}));
const H={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PATCH,OPTIONS','access-control-allow-headers':'authorization,content-type'};
// few badges to test short-content case
function summary(n){const badges=[];for(let i=0;i<n;i++)badges.push({id:'b'+i,title:'Achievement '+i,description:'Earn badge '+i+'.',category:'submissions',tier:'bronze',glyph:'submission',threshold:10,progress:5,points:10,secret:false,unlocked:i<1,clueGrowlix:''});return{ok:true,catalogVersion:'2026.03.v1',totals:{unlocked:1,total:n,points:30},metrics:{submissionsTotal:1,releasesTotal:0,pollVotes:0,favoritesCount:0},badges,newlyUnlocked:[],warnings:[]};}
await p.route('https://dex-api.spring-fog-8edd.workers.dev/**',async r=>{const path=new URL(r.request().url()).pathname;const j=x=>r.fulfill({status:200,headers:H,contentType:'application/json',body:JSON.stringify(x)});if(r.request().method()==='OPTIONS')return r.fulfill({status:204,headers:H});if(path.startsWith('/me/achievements/summary'))return j(summary(2));if(path.startsWith('/me/achievements/history'))return j({ok:true,events:[],nextCursor:''});if(path.startsWith('/me/achievements'))return j({ok:true});return j({ok:true});});
await p.goto(base+'/entry/achievements/',{waitUntil:'domcontentloaded'});await p.waitForTimeout(4000);
const m=await p.evaluate(()=>{const r=document.querySelector('#dex-achv');const cs=r?getComputedStyle(r):null;const rr=r?r.getBoundingClientRect():null;return {bodyClass:document.body.className,achvH:rr?Math.round(rr.height):null,achvTop:rr?Math.round(rr.top):null,achvBottom:rr?Math.round(rr.bottom):null,css:cs?{height:cs.height,maxHeight:cs.maxHeight,minHeight:cs.minHeight,overflow:cs.overflow,display:cs.display}:null,docH:document.documentElement.scrollHeight,winH:innerHeight};});
console.log(JSON.stringify(m,null,1));
await p.screenshot({path:'/private/tmp/claude-501/-Users-seb-dexdsl-github-io/dd139c6a-fa1d-46ff-8d5d-76a99e4f4a6f/scratchpad/achv-fewbadges.png',fullPage:true});
await b.close();
